//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerApplication.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class claim
    {
        public int id { get; set; }
        public string theme { get; set; }
        public string description { get; set; }
        public System.DateTime created_date { get; set; }
        public int initiator { get; set; }
        public int category { get; set; }
        public Nullable<System.DateTime> approved_date { get; set; }
        public Nullable<int> dispatcher { get; set; }
        public Nullable<int> department { get; set; }
        public Nullable<System.DateTime> finished_date { get; set; }
        public Nullable<System.DateTime> executed_date { get; set; }
        public Nullable<int> executor { get; set; }
        public int status { get; set; }
        public Nullable<int> contractor { get; set; }
        public int type { get; set; }
        public Nullable<System.DateTime> closed_date { get; set; }
        public Nullable<System.DateTime> confirmed_date { get; set; }
    
        public virtual category category_nav { get; set; }
        public virtual contractor contractor_nav { get; set; }
        public virtual department department_nav { get; set; }
        public virtual employee initiator_nav { get; set; }
        public virtual employee dispatcher_nav { get; set; }
        public virtual employee executor_nav { get; set; }
        public virtual status status_nav { get; set; }
        public virtual type type_nav { get; set; }
    }
}
